// Slug generation + uniqueness against ALL known articles from every source:
// BabyLoveGrowth's 28 (25 published, captured in the committed redacted
// baseline, plus 3 unpublished that were never in that file — see below),
// anything already generated by this pipeline, and whatever's currently
// built into src/data/blog-articles.json.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const BASELINE_PATH = path.join(PROJECT_ROOT, 'tools', 'blog-compliance', 'pre-regeneration-baseline.json');
const GENERATED_DIR = path.join(PROJECT_ROOT, 'src', 'data', 'generated-articles');
const BLOG_ARTICLES_PATH = path.join(PROJECT_ROOT, 'src', 'data', 'blog-articles.json');
// Optional, local-only, gitignored — present only on a machine that ran
// write-fixture.mjs. Never required (CI won't have it); used as an extra
// safety net during local dev when present.
const LOCAL_FIXTURE_PATH = path.join(PROJECT_ROOT, 'tools', 'blog-compliance', '.articles-cache.json');

// pre-regeneration-baseline.json (committed, slug-only, no content) was
// captured published-only at the time, so it has 25 of BabyLoveGrowth's 28
// known slugs. These 3 were confirmed live via the API during the
// 2026-07-25 acceptance-test session (still unpublished, never in the
// baseline file) — listed here as plain strings (no content) so CI-side
// uniqueness checking covers all 28 without needing the gitignored local
// fixture.
export const KNOWN_UNPUBLISHED_BABYLOVE_SLUGS = [
  'hot-market-home-buying-best-practices',
  'what-is-a-real-estate-portfolio',
  'what-is-a-real-estate-market-snapshot',
];

function readJsonSafe(filePath) {
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    return null;
  }
}

export function getKnownSlugs() {
  const slugs = new Set(KNOWN_UNPUBLISHED_BABYLOVE_SLUGS);

  const baseline = readJsonSafe(BASELINE_PATH);
  const baselineArticles = baseline?.articles || (Array.isArray(baseline) ? baseline : []);
  for (const a of baselineArticles || []) {
    if (a?.slug) slugs.add(a.slug);
  }

  if (fs.existsSync(GENERATED_DIR)) {
    for (const file of fs.readdirSync(GENERATED_DIR)) {
      if (!file.endsWith('.json')) continue;
      const a = readJsonSafe(path.join(GENERATED_DIR, file));
      if (a?.slug) slugs.add(a.slug);
    }
  }

  const blogArticles = readJsonSafe(BLOG_ARTICLES_PATH);
  for (const a of blogArticles || []) {
    if (a?.slug) slugs.add(a.slug);
  }

  if (fs.existsSync(LOCAL_FIXTURE_PATH)) {
    const fixture = readJsonSafe(LOCAL_FIXTURE_PATH);
    for (const a of fixture?.articles || []) {
      if (a?.slug) slugs.add(a.slug);
    }
  }

  return slugs;
}

export function slugify(text) {
  return String(text)
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip combining diacritics left by NFKD
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-');
}

// Deterministically resolves a collision by appending -2, -3, ... — never
// asks the model to guess uniqueness, since the code can just check.
export function uniqueSlug(candidate, knownSlugs) {
  const base = slugify(candidate);
  if (!knownSlugs.has(base)) return base;
  let n = 2;
  while (knownSlugs.has(`${base}-${n}`)) n += 1;
  return `${base}-${n}`;
}
